create table if not exists "FaltaJugadorPartido" (
  "id" bigint generated by default as identity primary key,
  "deporte" text not null,
  "nivel" text not null default 'Recreativo',
  "fecha" date not null,
  "horario" time not null,
  "jugadoresFaltantes" integer not null check ("jugadoresFaltantes" >= 0),
  "estado" text not null default 'abierto' check ("estado" in ('abierto', 'completo', 'cancelado')),
  "idComunidad" bigint not null references "Comunidad"("id"),
  "idCreador" bigint references "ComunidadUsuario"("id"),
  "fechaDeAlta" timestamptz not null default now()
);

create table if not exists "FaltaJugadorParticipante" (
  "id" bigint generated by default as identity primary key,
  "idPartido" bigint not null references "FaltaJugadorPartido"("id") on delete cascade,
  "idComunidadUsuario" bigint not null references "ComunidadUsuario"("id"),
  "fechaDeAlta" timestamptz not null default now(),
  constraint "FaltaJugadorParticipante_unico" unique ("idPartido", "idComunidadUsuario")
);

create index if not exists "idx_falta_jugador_partido_comunidad_deporte"
  on "FaltaJugadorPartido" ("idComunidad", "deporte", "estado");

create index if not exists "idx_falta_jugador_participante_partido"
  on "FaltaJugadorParticipante" ("idPartido");
